### ISSUE TITLE
debug_traceTransaction panics for some tracers.

### ISSUE THREAD

**Issue by piersy** [celo-org/celo-blockchain#1530]
## Expected Behavior

debug_traceTransaction should not panic regardless of the tracer used.

## Current Behavior

It panics on certain tracers.  We were facing this [issue](https://github.com/blockscout/blockscout/pull/3702) or a very similar one.

We were seeing this panic in the logs visible [here](https://console.cloud.google.com/logs/query;query=severity%3DERROR%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22geth%22%0AjsonPayload.msg%3D~%22RPC%20method%20debug_traceTransaction%20crashed%22;timeRange=2021-05-03T15:24:39.248Z%2F2021-05-03T16:24:39.248Z;cursorTimestamp=2021-05-03T16:24:23.240803275Z?project=celo-testnet-production&query=%0A)
```
RPC method debug_traceTransaction crashed: runtime error: invalid memory address or nil pointer dereference
goroutine 11582065 [running]:
github.com/celo-org/celo-blockchain/rpc.(*callback).call.func1(0xc041a10048, 0x16, 0xc015f35d28)
	/go-ethereum/rpc/service.go:200 +0xbd
panic(0x14e3520, 0x1f8d0f0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/celo-org/celo-blockchain/eth/tracers.(*dbWrapper).pushObject.func3(0xc0364280c0, 0x77cb62080)
	/go-ethereum/eth/tracers/tracer.go:213 +0xfb
gopkg.in/olebedev/go-duktape%2ev3.goFunctionCall(0xb51e5c480, 0x410a7b)
	/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200316214253-d7b0ff38cac9/duktape.go:156 +0xb8
gopkg.in/olebedev/go-duktape%2ev3._Cfunc_duk_pcall_prop(0xb51e5c480, 0x200000000, 0x0)
	_cgo_gotypes.go:2330 +0x48
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PcallProp.func1(0xc036428078, 0x0, 0x2, 0x77cb78200)
	/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200316214253-d7b0ff38cac9/api.go:786 +0x71
gopkg.in/olebedev/go-duktape%2ev3.(*Context).PcallProp(0xc036428078, 0x0, 0x2, 0x2)
	/go/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200316214253-d7b0ff38cac9/api.go:786 +0x3f
github.com/celo-org/celo-blockchain/eth/tracers.(*Tracer).call(0xc06970e210, 0x165c533, 0x6, 0xc015f2e3a0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/go-ethereum/eth/tracers/tracer.go:513 +0x110
github.com/celo-org/celo-blockchain/eth/tracers.(*Tracer).GetResult(0xc06970e210, 0x1855328, 0xc0611fc100, 0xc042fe0ea8, 0xc00067f830, 0x0)
	/go-ethereum/eth/tracers/tracer.go:641 +0x458
github.com/celo-org/celo-blockchain/eth.(*PrivateDebugAPI).traceTx(0xc00048fa38, 0x1846d78, 0xc008c18200, 0x1855328, 0xc0611fc100, 0x16e6ae0, 0x16e6b00, 0xc030ba98c0, 0xc044a462e8, 0xc05c3b42a0, ...)
	/go-ethereum/eth/api_tracer.go:776 +0x752
github.com/celo-org/celo-blockchain/eth.(*PrivateDebugAPI).TraceTransaction(0xc00048fa38, 0x1846d78, 0xc008c18200, 0x45ca38dfdcd49f84, 0x328d857837ea8b87, 0x7fab351c4237093a, 0x14a95a3770a151ea, 0xc05c3b40a0, 0x0, 0x0, ...)
	/go-ethereum/eth/api_tracer.go:719 +0x2d0
reflect.Value.call(0xc005e93500, 0xc005e8d658, 0x13, 0x1659814, 0x4, 0xc06518e2a0, 0x4, 0x4, 0xc06518e2d0, 0xc030ba8e40, ...)
	/usr/local/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc005e93500, 0xc005e8d658, 0x13, 0xc06518e2a0, 0x4, 0x4, 0x0, 0x0, 0xc00aaf8e00)
	/usr/local/go/src/reflect/value.go:337 +0xb9
github.com/celo-org/celo-blockchain/rpc.(*callback).call(0xc005ed9b60, 0x1846d78, 0xc008c18200, 0xc041a10048, 0x16, 0xc030ba8e40, 0x2, 0x2, 0x0, 0x0, ...)
	/go-ethereum/rpc/service.go:206 +0x2c5
github.com/celo-org/celo-blockchain/rpc.(*handler).runMethod(0xc0384d4c60, 0x1846d78, 0xc008c18200, 0xc07290a0e0, 0xc005ed9b60, 0xc030ba8e40, 0x2, 0x2, 0x2)
	/go-ethereum/rpc/handler.go:389 +0x8a
github.com/celo-org/celo-blockchain/rpc.(*handler).handleCall(0xc0384d4c60, 0xc030ba8c60, 0xc07290a0e0, 0x8)
	/go-ethereum/rpc/handler.go:337 +0x265
github.com/celo-org/celo-blockchain/rpc.(*handler).handleCallMsg(0xc0384d4c60, 0xc030ba8c60, 0xc07290a0e0, 0xc036428018)
	/go-ethereum/rpc/handler.go:298 +0x1be
github.com/celo-org/celo-blockchain/rpc.(*handler).handleBatch.func2(0xc030ba8c60)
	/go-ethereum/rpc/handler.go:119 +0xf6
github.com/celo-org/celo-blockchain/rpc.(*handler).startCallProc.func1(0xc0384d4c60, 0xc008c181c0)
	/go-ethereum/rpc/handler.go:226 +0xd2
created by github.com/celo-org/celo-blockchain/rpc.(*handler).startCallProc
	/go-ethereum/rpc/handler.go:222 +0x66
```

the panic appears to be occurring here:

https://github.com/celo-org/celo-blockchain/blob/ede6fa241231e232213739217a33311993957540/eth/tracers/tracer.go#L213

It looks like this occurs when tracing a contract creation without code.

## Steps to Reproduce Behavior

Use the tracer [here](https://github.com/celo-org/blockscout/blob/4681cef68a41038955b4bd52e18028b5678db3a8/apps/ethereum_jsonrpc/priv/js/ethereum_jsonrpc/geth/debug_traceTransaction/tracer.js) in a call to `debug_traceTransaction` for this tx `0x62fc6c80afa9acd1ba04f5d8cf1453feb5273e704421f47b6d4e2815757573db`.

## System information

v1.3.0

**Comment by palango** [comment]
Probably fixed with https://github.com/celo-org/celo-blockchain/pull/2137.
