### ISSUE TITLE
Panic in istanbul/backend tests

### ISSUE THREAD

**Issue by piersy** [celo-org/celo-blockchain#1601]
## Description

While running the tests on master 4e42e7e8d683929b1317859d86431d5b3d3037c6, I received the following errror.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9d70e2]

goroutine 922 [running]:
github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).newChainHeadLoop(0xc013930000, 0xc0149e2000)
	/home/piersy/projects/celo-blockchain/consensus/istanbul/backend/engine.go:607 +0x82
created by github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).SetChain
	/home/piersy/projects/celo-blockchain/consensus/istanbul/backend/engine.go:596 +0x96
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9d7368]

goroutine 923 [running]:
github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).updateReplicaStateLoop(0xc013930000, 0xc0149e2000)
	/home/piersy/projects/celo-blockchain/consensus/istanbul/backend/engine.go:625 +0x88
created by github.com/celo-org/celo-blockchain/consensus/istanbul/backend.(*Backend).SetChain
	/home/piersy/projects/celo-blockchain/consensus/istanbul/backend/engine.go:597 +0xc5
FAIL	github.com/celo-org/celo-blockchain/consensus/istanbul/backend	80.643s
```

**Comment by YoduYodu** [comment]
The may be related to races in tests of `consensus/istanbul/backend`
