### ISSUE TITLE
BREAKING BUG - Panic in Celo 1.5.0

### ISSUE THREAD

**Issue by gentrysherrill** [celo-org/celo-blockchain#1799]
## Description

After upgrading from 1.4.1 to 1.5.0, we've begun to see periodic failures of our Celo node

Typically these are panics with very long stack traces / debug logging; a partial example of one occurring shortly after start up is included below

```
INFO [01-20|19:43:25.904] Allocated cache and file handles         database=/root/.celo/celo/les.server   cache=16.00MiB handles=16
INFO [01-20|19:43:25.917] Checkpoint oracle is not enabled
INFO [01-20|19:43:25.920] Loaded latest checkpoint                 section=335 head=d9af17..f57942 chtroot=ff544c..81c633 bloomroot=eabd99..0ab722
INFO [01-20|19:43:25.920] Starting peer-to-peer node               instance=celo/v1.5.0-stable/linux-amd64/go1.16.13
INFO [01-20|19:43:25.946] New local node record                    seq=106,674 id=aa1c7a6ffd11bb5e ip=127.0.0.1 udp=30303 tcp=30303
INFO [01-20|19:43:25.957] Started P2P networking                   self=enode://01663c04afc7102a8a622bcca89b601a595942b2ca5475bfef1aca3d467598181dc34712677226d36971bb4636e0640035bed5363afe8e407aff9735787c2bd0@127.0.0.1:30303 maxdialed=33 maxinbound=267
INFO [01-20|19:43:25.959] IPC endpoint opened                      url=/root/.celo/geth.ipc
INFO [01-20|19:43:25.960] HTTP server started                      endpoint=[::]:8545 prefix= cors= vhosts=localhost
INFO [01-20|19:43:26.154] Block synchronisation started
INFO [01-20|19:43:38.660] Looking for peers                        peercount=0 tried=91 static=0
INFO [01-20|19:43:50.108] Looking for peers                        peercount=0 tried=81 static=0
INFO [01-20|19:44:00.957] Looking for peers                        peercount=0 tried=36 static=0
INFO [01-20|19:44:11.366] Looking for peers                        peercount=1 tried=58 static=0
INFO [01-20|19:44:22.300] Looking for peers                        peercount=2 tried=70 static=0
WARN [01-20|19:44:26.155] Synchronisation failed, dropping peer    peer=999dd022d9449da7a3dfe63f711ff70b78499f02b2a290725d0ac67ba0440031 err=timeout
ERROR[01-20|19:44:26.155] Ethereum peer removal failed             peer=999dd022 err="peer not registered"
INFO [01-20|19:44:32.313] Looking for peers                        peercount=2 tried=53 static=0
ERROR[01-20|19:44:40.672] Transaction failed to buy gas            err="insufficient funds for gas * price + value + gatewayFee: address 0x63A090322a16cA3BD4685F8E393A6C8c575dceB9 have 17087872187824 want 86815735712608" gas=71668
INFO [01-20|19:44:42.379] Looking for peers                        peercount=2 tried=59 static=0
INFO [01-20|19:44:53.424] Looking for peers                        peercount=2 tried=22 static=0
INFO [01-20|19:45:03.581] Looking for peers                        peercount=2 tried=22 static=0
fatal error: concurrent map read and map write

goroutine 11314 [running]:
runtime.throw(0x17e87ae, 0x21)
	runtime/panic.go:1117 +0x72 fp=0xc0650ce5f0 sp=0xc0650ce5c0 pc=0x445332
runtime.mapaccess1(0x160fdc0, 0xc04b75cea0, 0xc0650ce6d4, 0xc0003682c0)
	runtime/map.go:411 +0x247 fp=0xc0650ce630 sp=0xc0650ce5f0 pc=0x41c1c7
github.com/celo-org/celo-blockchain/core/state.(*StateDB).getDeletedStateObject(0xc064f7ea80, 0x0, 0x0, 0xc010ce0000, 0x0)
	github.com/celo-org/celo-blockchain/core/state/statedb.go:505 +0xb5 fp=0xc0650ce880 sp=0xc0650ce630 pc=0xadc635
github.com/celo-org/celo-blockchain/core/state.(*StateDB).getStateObject(...)
	github.com/celo-org/celo-blockchain/core/state/statedb.go:493
github.com/celo-org/celo-blockchain/core/state.(*StateDB).GetState(0xc064f7ea80, 0x0, 0x0, 0xa194083610ce0000, 0x28c8670621a3a13b, 0x76203eca8db92d49, 0x50caa320a93537cc, 0xc0bc2b385d, 0x0, 0x0, ...)
	github.com/celo-org/celo-blockchain/core/state/statedb.go:304 +0x85 fp=0xc0650ce920 sp=0xc0650ce880 pc=0xadac05
github.com/celo-org/celo-blockchain/core/vm.opSload(0xc065093570, 0xc0650ea900, 0xc0581b90e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/celo-org/celo-blockchain/core/vm/instructions.go:500 +0x13e fp=0xc0650cea40 sp=0xc0650ce920 pc=0xb4e57e
github.com/celo-org/celo-blockchain/core/vm.(*EVMInterpreter).Run(0xc0650ea900, 0xc0650f40c0, 0xc0650d43a9, 0x24, 0xd7, 0xa01, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/celo-org/celo-blockchain/core/vm/interpreter.go:262 +0x525 fp=0xc0650cecd0 sp=0xc0650cea40 pc=0xb54185
github.com/celo-org/celo-blockchain/core/vm.(*EVM).StaticCall(0xc0650ee000, 0x1996a40, 0xc0650f4000, 0x0, 0x0, 0x541d1a7d10ce0000, 0xc0650d43a9, 0x24, 0xd7, 0x1d82c6, ...)
	github.com/celo-org/celo-blockchain/core/vm/evm.go:393 +0x5be fp=0xc0650cee50 sp=0xc0650cecd0 pc=0xb44f5e
github.com/celo-org/celo-blockchain/core/vm.opStaticCall(0xc065093568, 0xc0650ea900, 0xc0581b90c8, 0xc0650da180, 0xe0, 0x1d82c6, 0x0, 0x0)
	github.com/celo-org/celo-blockchain/core/vm/instructions.go:750 +0x511 fp=0xc0650cf1a8 sp=0xc0650cee50 pc=0xb52631
github.com/celo-org/celo-blockchain/core/vm.(*EVMInterpreter).Run(0xc0650ea900, 0xc0650f4000, 0xc0650f0080, 0x24, 0x40, 0x2100, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/celo-org/celo-blockchain/core/vm/interpreter.go:262 +0x525 fp=0xc0650cf438 sp=0xc0650cf1a8 pc=0xb54185
github.com/celo-org/celo-blockchain/core/vm.(*EVM).DelegateCall(0xc0650ee000, 0x1996a40, 0xc060fb9ec0, 0xcab5bd1ddf94417c, 0x7601b07b457d7b73, 0x6123a5f8, 0xc0650f0080, 0x24, 0x40, 0x1e0367, ...)
	github.com/celo-org/celo-blockchain/core/vm/evm.go:342 +0x5de fp=0xc0650cf5b0 sp=0xc0650cf438 pc=0xb4481e
github.com/celo-org/celo-blockchain/core/vm.opDelegateCall(0xc065093560, 0xc0650ea900, 0xc0581b90b0, 0xc0650da160, 0xc0, 0x1e0367, 0x0, 0x0)
	github.com/celo-org/celo-blockchain/core/vm/instructions.go:720 +0x511 fp=0xc0650cf908 sp=0xc0650cf5b0 pc=0xb51c51
github.com/celo-org/celo-blockchain/core/vm.(*EVMInterpreter).Run(0xc0650ea900, 0xc060fb9ec0, 0xc061381ac0, 0x24, 0x40, 0xa01, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/celo-org/celo-blockchain/core/vm/interpreter.go:262 +0x525 fp=0xc0650cfb98 sp=0xc0650cf908 pc=0xb54185
github.com/celo-org/celo-blockchain/core/vm.(*EVM).StaticCall(0xc0650ee000, 0x1998b40, 0xc047539938, 0xbad899768d3acadf, 0x7cc160ad236865fe, 0xcc0e27b8, 0xc061381ac0, 0x24, 0x40, 0x1e8480, ...)
	github.com/celo-org/celo-blockchain/core/vm/evm.go:393 +0x5be fp=0xc0650cfd18 sp=0xc0650cfb98 pc=0xb44f5e
github.com/celo-org/celo-blockchain/core/vm/vmcontext.(*evmRunner).Query(0xc066ba5400, 0xbad899768d3acadf, 0x7cc160ad236865fe, 0xcc0e27b8, 0xc061381ac0, 0x24, 0x40, 0x1e8480, 0x0, 0x0, ...)
	github.com/celo-org/celo-blockchain/core/vm/vmcontext/runner.go:74 +0x125 fp=0xc0650cfdc8 sp=0xc0650cfd18 pc=0xbaa365
github.com/celo-org/celo-blockchain/contracts.(*BoundMethod).run(0xc0003791d0, 0x19b7038, 0xc066ba5400, 0x156f3a0, 0xc064fc9e40, 0xafbf87066c0c2b01, 0x0, 0xc04e2ec8c0, 0x1, 0x1, ...)
	github.com/celo-org/celo-blockchain/contracts/contract_call.go:103 +0x3d3 fp=0xc0650d05b8 sp=0xc0650cfdc8 pc=0xba6353
github.com/celo-org/celo-blockchain/contracts.(*BoundMethod).Query(...)
	github.com/celo-org/celo-blockchain/contracts/contract_call.go:76
github.com/celo-org/celo-blockchain/contracts/gasprice_minimum.GetGasPriceMinimum(0x19b7038, 0xc066ba5400, 0x0, 0x14, 0x23550ad90f, 0xc0728cd249e55ccf)
	github.com/celo-org/celo-blockchain/contracts/gasprice_minimum/gasprice_minimum.go:80 +0x17b fp=0xc0650d0698 sp=0xc0650d05b8 pc=0xbe28bb
github.com/celo-org/celo-blockchain/core.NewStateTransition(0xc0650c8000, 0x19c6d30, 0xc0541a9540, 0xc0650934e0, 0x19b7038, 0xc066ba5400, 0x0, 0x2)
	github.com/celo-org/celo-blockchain/core/state_transition.go:214 +0x48a fp=0xc0650d0740 sp=0xc0650d0698 pc=0xc1084a
github.com/celo-org/celo-blockchain/core.ApplyMessage(0xc0650c8000, 0x19c6d30, 0xc0541a9540, 0xc0650934e0, 0x19b7038, 0xc066ba5400, 0x0, 0x8b98da9c, 0xc05fdb3460, 0xc05fdb3480)
	github.com/celo-org/celo-blockchain/core/state_transition.go:242 +0x53e fp=0xc0650d0960 sp=0xc0650d0740 pc=0xc10dde
github.com/celo-org/celo-blockchain/eth/tracers.(*API).traceTx(0xc0002ddb70, 0x19b4198, 0xc05f4c3580, 0x19c6d30, 0xc0541a9540, 0xc032dcbcf8, 0x184dac0, 0x184dae8, 0xc04b75d020, 0xc0578badc8, ...)
	github.com/celo-org/celo-blockchain/eth/tracers/api.go:872 +0x4a5 fp=0xc0650d1be0 sp=0xc0650d0960 pc=0xe68dc5
github.com/celo-org/celo-blockchain/eth/tracers.(*API).traceBlock.func1(0xc05fdb8800, 0xc014034900, 0xc05591f300, 0xf, 0xf, 0x19b7738, 0xc05cef8690, 0xc0002ddb70, 0xc05591f380, 0xc064f7ea80, ...)
	github.com/celo-org/celo-blockchain/eth/tracers/api.go:550 +0x39e fp=0xc0650d1ec8 sp=0xc0650d1be0 pc=0xe70f1e
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc0650d1ed0 sp=0xc0650d1ec8 pc=0x47f521
created by github.com/celo-org/celo-blockchain/eth/tracers.(*API).traceBlock
	github.com/celo-org/celo-blockchain/eth/tracers/api.go:539 +0x705
```

The node seems to attempt to restart itself when this happens (which is odd in and of itself - I would expect the process (or in our case docker container) to die), however it is not usually successful

We'll often see several cycles of panics, restarts, and long periods of being unable to connect to peers effectively before beginning to download block activity; usually this can be resolved by completely stopping and removing the docker container and then starting one up "fresh", though it usually takes 20 - 30 minutes at start up for the node to connect to enough peers to start adding data again

## Context

Celo version 1.5.0-stable, running in docker image us.gcr.io/celo-org/geth:1.5.0

Docker version 19.03.6

Machine is running Ubuntu 18.04.4 LTS

Happy to share any additional information if helpful

**Comment by gentrysherrill** [comment]
As an addendum, this issue is now happening shortly after start up consistently and we are unable to sync new blocks

Have also noticed (likely unrelated) errors like these in the node logs:

```
ERROR[01-20|20:38:12.818] Transaction failed to buy gas            err="insufficient funds for gas * price + value + gatewayFee: address 0x40338eFdD9C287bD25898E2CC443Deb7e9f448eC have 15277313778540 want 88459565226720" gas=71668
ERROR[01-20|20:38:12.822] Transaction failed to buy gas            err="insufficient funds for gas * price + value + gatewayFee: address 0x04Dd2b249554ABB3A91e0526B1cCcfe6eD9C1c59 have 17276358909282 want 100024061264424" gas=71656
```

**Comment by gentrysherrill** [comment]
Actually seeing the same behavior now on version 1.4.1

**Comment by piersy** [comment]
@gentrysherrill There is a PR to fix this #1822 would be great if you could verify if it is solving your problem!

**Comment by gentrysherrill** [comment]
@piersy We actually run Celo in docker via the celo-labs geth image, so not a clean way for me to test quickly

When I have time later in the week will clone the repo and build from source to test out the fix; I'm betting it works though, moving the statedb read to use those thread-specific `innerStatedb` instances should prevent the concurrency issues

**Comment by gentrysherrill** [comment]
Can confirm the change seems to fix the issue, or at least mitigates it to the degree that I haven't been able to reproduce under similar circumstances and load @piersy

**Comment by piersy** [comment]
@gentrysherrill Thank you for confirming, this issue will get closed automatically when the associated PR is merged into our master branch.
