### ISSUE TITLE
v1.7.0 seg fault after "Error in retrieving exchange rate", crashed validator

### ISSUE THREAD

**Issue by aaronmboyd** [celo-org/celo-blockchain#1982]
## Description

Seg fault stopped validator from signing blocks, restart loop that needed restart of proxy and validator to recover.

## Context

Note: this is a ARM64 build from Release tag v1.7.0, running on Ubuntu 22.04+

```
INFO [11-23|13:10:21.769] Deep froze chain segment                 blocks=353 elapsed=91.739ms  number=16,217,859 hash=20b366..cad266
WARN [11-23|13:10:27.392] Error in retrieving exchange rate.  Will do comparison of two values without exchange rate conversion. currency1=0x765DE816845861e75A25fCA122bb6898B8B1282a err1="Exchange rate returned from the network is zero" currency2=nil err2=nil
WARN [11-23|13:10:27.393] Error in retrieving exchange rate.  Will do comparison of two values without exchange rate conversion. currency1=nil err1=nil currency2=0x765DE816845861e75A25fCA122bb6898B8B1282a err2="Exchange rate returned from the network is zero"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc4ae18]
goroutine 624 [running]:
github.com/celo-org/celo-blockchain/contracts/currency.(*Currency).ToCELO(...)
	github.com/celo-org/celo-blockchain/contracts/currency/currency.go:62
github.com/celo-org/celo-blockchain/miner.createConversionFunctions.func2(0x72713bab?, 0x4015579c60?)
	github.com/celo-org/celo-blockchain/miner/block.go:380 +0x28
github.com/celo-org/celo-blockchain/core/types.NewTxWithMinerFee(0x4005f4b8c0, 0x405b12f170, 0x405b12f180)
	github.com/celo-org/celo-blockchain/core/types/transaction.go:555 +0x88
github.com/celo-org/celo-blockchain/core/types.NewTransactionsByPriceAndNonce({0x1917a20?, 0x4034c91e40}, 0x4063bcb620, 0x405b12f170, 0x405b12f180)
	github.com/celo-org/celo-blockchain/core/types/transaction.go:609 +0x168
github.com/celo-org/celo-blockchain/miner.(*worker).constructPendingStateBlock(0x400a047680, {0x19151b8, 0x404076ce80}, 0x400a89e9c0)
	github.com/celo-org/celo-blockchain/miner/worker.go:363 +0x408
github.com/celo-org/celo-blockchain/miner.(*worker).mainLoop.func1.2()
	github.com/celo-org/celo-blockchain/miner/worker.go:412 +0x38
created by github.com/celo-org/celo-blockchain/miner.(*worker).mainLoop.func1
	github.com/celo-org/celo-blockchain/miner/worker.go:411 +0x1f4
```

## Proposed Solution

Pending

**Comment by palango** [comment]
Closing because we reimplemented that code for the L2.
