### ISSUE TITLE
Validator SBAT run stable

### ISSUE THREAD

**Issue by rcroessmann** [celo-org/celo-blockchain#401]
### Expected Behavior

The validator node should run in a stable and robust way.

### Current Behavior

The validator crashed and restarting the validator was unsuccessful. The logs of the crash:
````
goroutine 112878756 [select]:
github.com/ethereum/go-ethereum/p2p.(*protoRW).ReadMsg(0xc06ea8fd40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x30c7e7d64a64f)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:431 +0x101
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handleMsg(0xc0004bb1d0, 0xc0638d0300, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:361 +0xa6
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handle(0xc0004bb1d0, 0xc0638d0300, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:350 +0x90e
github.com/ethereum/go-ethereum/eth.NewProtocolManager.func1(0xc0780ae5a0, 0x1279c00, 0xc06ea8fd40, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:166 +0x1b8
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc06ea8fd40, 0xc0780ae5a0, 0x1279c00, 0xc06ea8fd40)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:377 +0x66
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:376 +0x1fb

goroutine 91768178 [IO wait]:
internal/poll.runtime_pollWait(0x7fb0030736e0, 0x72, 0xc0460dbb28)
        /usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00ba28f98, 0x72, 0xffffffffffffff00, 0x1278100, 0x19f6c48)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00ba28f98, 0xc0a5bcf900, 0x20, 0x20)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00ba28f80, 0xc0a5bcf920, 0x20, 0x20, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc00ba28f80, 0xc0a5bcf920, 0x20, 0x20, 0x7faffd96f161, 0x442c02, 0xc9)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc042269288, 0xc0a5bcf920, 0x20, 0x20, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:177 +0x68
io.ReadAtLeast(0x1276b80, 0xc042269288, 0xc0a5bcf920, 0x20, 0x20, 0x20, 0xfcd5e0, 0xc00ba28f00, 0x1276b80)
        /usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(0x1276b80, 0xc042269288, 0xc0a5bcf920, 0x20, 0x20, 0x20, 0xc00ba28f80, 0xbf4726c1534f9cb2)
        /usr/local/go/src/io/io.go:329 +0x58
github.com/ethereum/go-ethereum/p2p.(*rlpxFrameRW).ReadMsg(0xc068482b60, 0xbf4726c1534f9cb2, 0x30c8579892ab8, 0x1d6bb80, 0x0, 0x0, 0x1d6bb80, 0x0, 0x11, 0x27)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:648 +0xfd
github.com/ethereum/go-ethereum/p2p.(*rlpx).ReadMsg(0xc069dd9cb0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:95 +0x127
github.com/ethereum/go-ethereum/p2p.(*Peer).readLoop(0xc00ba27980, 0xc00ba27bc0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:273 +0xa6
created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:210 +0xf8

goroutine 92253444 [select]:
github.com/ethereum/go-ethereum/p2p.(*Peer).pingLoop(0xc032eacc00)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:257 +0x143
created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:211 +0x11d
roman@pecon-validator:~/celo-data-dir$

goroutine 110407361 [select]:
github.com/ethereum/go-ethereum/p2p.(*protoRW).ReadMsg(0xc01b6c9170, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x30c7e7c4b4092)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:431 +0x101
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handleMsg(0xc0004bb1d0, 0xc04dcbc840, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:361 +0xa6
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handle(0xc0004bb1d0, 0xc04dcbc840, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:350 +0x90e
github.com/ethereum/go-ethereum/eth.NewProtocolManager.func1(0xc08f290de0, 0x1279c00, 0xc01b6c9170, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:166 +0x1b8
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc01b6c9170, 0xc08f290de0, 0x1279c00, 0xc01b6c9170)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:377 +0x66
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:376 +0x1fb

goroutine 112878756 [select]:
github.com/ethereum/go-ethereum/p2p.(*protoRW).ReadMsg(0xc06ea8fd40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x30c7e7d64a64f)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:431 +0x101
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handleMsg(0xc0004bb1d0, 0xc0638d0300, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:361 +0xa6
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handle(0xc0004bb1d0, 0xc0638d0300, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:350 +0x90e
github.com/ethereum/go-ethereum/eth.NewProtocolManager.func1(0xc0780ae5a0, 0x1279c00, 0xc06ea8fd40, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:166 +0x1b8
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc06ea8fd40, 0xc0780ae5a0, 0x1279c00, 0xc06ea8fd40)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:377 +0x66
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:376 +0x1fb

goroutine 91768178 [IO wait]:
internal/poll.runtime_pollWait(0x7fb0030736e0, 0x72, 0xc0460dbb28)
        /usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00ba28f98, 0x72, 0xffffffffffffff00, 0x1278100, 0x19f6c48)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00ba28f98, 0xc0a5bcf900, 0x20, 0x20)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00ba28f80, 0xc0a5bcf920, 0x20, 0x20, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc00ba28f80, 0xc0a5bcf920, 0x20, 0x20, 0x7faffd96f161, 0x442c02, 0xc9)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc042269288, 0xc0a5bcf920, 0x20, 0x20, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:177 +0x68
io.ReadAtLeast(0x1276b80, 0xc042269288, 0xc0a5bcf920, 0x20, 0x20, 0x20, 0xfcd5e0, 0xc00ba28f00, 0x1276b80)
        /usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(0x1276b80, 0xc042269288, 0xc0a5bcf920, 0x20, 0x20, 0x20, 0xc00ba28f80, 0xbf4726c1534f9cb2)
        /usr/local/go/src/io/io.go:329 +0x58
github.com/ethereum/go-ethereum/p2p.(*rlpxFrameRW).ReadMsg(0xc068482b60, 0xbf4726c1534f9cb2, 0x30c8579892ab8, 0x1d6bb80, 0x0, 0x0, 0x1d6bb80, 0x0, 0x11, 0x27)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:648 +0xfd
github.com/ethereum/go-ethereum/p2p.(*rlpx).ReadMsg(0xc069dd9cb0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:95 +0x127
github.com/ethereum/go-ethereum/p2p.(*Peer).readLoop(0xc00ba27980, 0xc00ba27bc0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:273 +0xa6
created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:210 +0xf8

goroutine 92253444 [select]:
github.com/ethereum/go-ethereum/p2p.(*Peer).pingLoop(0xc032eacc00)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:257 +0x143
created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:211 +0x11d
roman@pecon-validator:~/celo-data-dir$
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:166 +0x1b8
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc01b6c9170, 0xc08f290de0, 0x1279c00, 0xc01b6c9170)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:377 +0x66
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:376 +0x1fb

goroutine 112878756 [select]:
github.com/ethereum/go-ethereum/p2p.(*protoRW).ReadMsg(0xc06ea8fd40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x30c7e7d64a64f)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:431 +0x101
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handleMsg(0xc0004bb1d0, 0xc0638d0300, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:361 +0xa6
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handle(0xc0004bb1d0, 0xc0638d0300, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:350 +0x90e
github.com/ethereum/go-ethereum/eth.NewProtocolManager.func1(0xc0780ae5a0, 0x1279c00, 0xc06ea8fd40, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:166 +0x1b8
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc06ea8fd40, 0xc0780ae5a0, 0x1279c00, 0xc06ea8fd40)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:377 +0x66
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:376 +0x1fb

goroutine 91768178 [IO wait]:
internal/poll.runtime_pollWait(0x7fb0030736e0, 0x72, 0xc0460dbb28)
        /usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00ba28f98, 0x72, 0xffffffffffffff00, 0x1278100, 0x19f6c48)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00ba28f98, 0xc0a5bcf900, 0x20, 0x20)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00ba28f80, 0xc0a5bcf920, 0x20, 0x20, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc00ba28f80, 0xc0a5bcf920, 0x20, 0x20, 0x7faffd96f161, 0x442c02, 0xc9)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc042269288, 0xc0a5bcf920, 0x20, 0x20, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:177 +0x68
io.ReadAtLeast(0x1276b80, 0xc042269288, 0xc0a5bcf920, 0x20, 0x20, 0x20, 0xfcd5e0, 0xc00ba28f00, 0x1276b80)
        /usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(0x1276b80, 0xc042269288, 0xc0a5bcf920, 0x20, 0x20, 0x20, 0xc00ba28f80, 0xbf4726c1534f9cb2)
        /usr/local/go/src/io/io.go:329 +0x58
github.com/ethereum/go-ethereum/p2p.(*rlpxFrameRW).ReadMsg(0xc068482b60, 0xbf4726c1534f9cb2, 0x30c8579892ab8, 0x1d6bb80, 0x0, 0x0, 0x1d6bb80, 0x0, 0x11, 0x27)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:648 +0xfd
github.com/ethereum/go-ethereum/p2p.(*rlpx).ReadMsg(0xc069dd9cb0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:95 +0x127
github.com/ethereum/go-ethereum/p2p.(*Peer).readLoop(0xc00ba27980, 0xc00ba27bc0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:273 +0xa6
created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:210 +0xf8

goroutine 92253444 [select]:
github.com/ethereum/go-ethereum/p2p.(*Peer).pingLoop(0xc032eacc00)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:257 +0x143
created by github.com/ethereum/go-ethereum/p2p.(*Peer).run
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:211 +0x11d
````

The logs of the unsuccessful restarting attempt:
````
roman@pecon-validator:~/celo-data-dir$ docker run -p 127.0.0.1:8545:8545 -p 127.0.0.1:8546:8546 -p 30303:30303 -p 30303:30303/udp -v `pwd`:/root/.celo us.gcr.io/celo-testnet/celo-node:alfajores --verbosity 3 --networkid 44781 --syncmode full --rpc --rpcaddr 0.0.0.0 --rpcapi eth,net,web3,debug,admin,personal --maxpeers 1100 --mine --miner.verificationpool=https://us-central1-celo-testnet-production.cloudfunctions.net/handleVerificationRequestalfajores/v0.1/sms/ --etherbase $CELO_VALIDATOR_ADDRESS
INFO [08-15|08:55:19.290] Maximum peer count                       ETH=1100 LES=0 total=1100
WARN [08-15|08:55:19.336] Found deprecated node list file /root/.celo/static-nodes.json, please use the TOML config file instead.
INFO [08-15|08:55:19.376] Starting peer-to-peer node               instance=Geth/v1.8.23-stable/linux-amd64/go1.11.12
INFO [08-15|08:55:19.377] Allocated cache and file handles         database=/root/.celo/geth/chaindata cache=768 handles=524288
INFO [08-15|08:55:19.556] Initialised chain configuration          config="{ChainID: 44781 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0  ConstantinopleFix: 0 Engine: istanbul}"
INFO [08-15|08:55:19.557] Initialising Ethereum protocol           versions=[64] network=44781
INFO [08-15|08:55:19.559] Loaded most recent local header          number=196434 hash=1da576…bcd26d td=196435 age=2w4d22h
INFO [08-15|08:55:19.560] Loaded most recent local full block      number=196434 hash=1da576…bcd26d td=196435 age=2w4d22h
INFO [08-15|08:55:19.560] Loaded most recent local fast block      number=196434 hash=1da576…bcd26d td=196435 age=2w4d22h
INFO [08-15|08:55:19.562] Loaded local transaction journal         transactions=0 dropped=0
INFO [08-15|08:55:19.563] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-15|08:55:20.019] New local node record                    seq=3 id=f245622dd63465fd ip=127.0.0.1 udp=30303 tcp=30303
INFO [08-15|08:55:20.041] Started P2P networking                   self=enode://01c07c187b6449ef1afdea0330d37b756b80406d95237972ef47cf4d4adaf04409097853a317310edf838c8f606da6f234dc8d1783fb895a18a2e6fbdcf9c486@127.0.0.1:30303
INFO [08-15|08:55:20.096] IPC endpoint opened                      url=/root/.celo/geth.ipc
INFO [08-15|08:55:20.098] HTTP endpoint opened                     url=http://0.0.0.0:8545  cors= vhosts=localhost
INFO [08-15|08:55:20.098] Transaction pool price threshold updated price=1
INFO [08-15|08:55:20.098] Transaction pool price threshold updated price=1
INFO [08-15|08:55:20.233] Commit new mining work                   number=196435 sealhash=3fe90b…e63f68 uncles=0 txs=0 gas=0 fees=0 elapsed=70.329ms
WARN [08-15|08:55:20.238] Block sealing failed                     err="authentication needed: password or unlock"
INFO [08-15|08:55:20.770] Block synchronisation started
INFO [08-15|08:55:20.772] Mining aborted due to sync
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xa9acad]

goroutine 241 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc018e62000, 0xc000f5a870, 0xc00165b200, 0x0, 0x0, 0x30)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:864 +0x15ad
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc018e62000, 0xc000f5a870, 0x5de4a43bdcf5334, 0xef467b0b9a37ff25, 0xfc9acda265cfe87b, 0x75be7df22aa1afc4, 0xc002382640, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:466 +0x37d
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc018e62000, 0xc000945a80, 0x10, 0x5de4a43bdcf5334, 0xef467b0b9a37ff25, 0xfc9acda265cfe87b, 0x75be7df22aa1afc4, 0xc002382640, 0x0, 0x0, ...)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:435 +0x362
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc018e62000, 0xc000945a80, 0x10, 0x5de4a43bdcf5334, 0xef467b0b9a37ff25, 0xfc9acda265cfe87b, 0x75be7df22aa1afc4, 0xc002382640, 0x0, 0xc01b391fc0, ...)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:353 +0x91
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0xc0189cbe00, 0xc000a203c0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:200 +0x313
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:151 +0x269
````

**Comment by ashishb** [comment]
@rcroessmann Have we seen this again? Is this still relevant?

**Comment by kevjue** [comment]
I'm going to close this issue as we haven't encountered it for a while.

@rcroessmann - Feel free to re-open if you think otherwise.
