### ISSUE TITLE
validator stopped after a few hours

### ISSUE THREAD

**Issue by mabalaru** [celo-org/celo-blockchain#698]
### Expected Behavior

Validator should stay online on it's own
### Current Behavior

What is the current behavior?
Validator stopped on it's own after a few working hours.
```
Error msg:
goroutine 3845721 [select]:
github.com/ethereum/go-ethereum/event.(*TypeMuxSubscription).deliver(0xc04c799320, 0xc284456b70)
    /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/event/event.go:213 +0x155
github.com/ethereum/go-ethereum/event.(*TypeMux).Post(0xc000561500, 0x1148c80, 0xc284444c60, 0x10b3a00, 0x1cffd81)
    /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/event/event.go:97 +0x18e
created by github.com/ethereum/go-ethereum/consensus/istanbul/backend.(*Backend).handleConsensusMsg
    /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/istanbul/backend/handler.go:138 +0x29c
stty: standard input: Not a tty
```
I was able to start it with `docker start celo-validator`

**Comment by tkporter** [comment]
Hey @mabalaru, thanks for the issue! Do you have any other logs from when it crashed?

**Comment by nategraf** [comment]
Since we don't have enough info to debug this issue, I am going to close it. @mabalaru feel free to reopen this if you can provide some more info.
