### ISSUE TITLE
Bad Block 59040 crashing node

### ISSUE THREAD

**Issue by daithi-coombes** [celo-org/celo-blockchain#710]
### Expected Behavior
Validator would sync and start mining

### Current Behavior
Validator tries to sync but is getting stuck with a bad block
After 10 mins geth crashes.

stdout:
```
Error: invalid receipt root hash (remote: 3ba70a8826bdb7e2f38a5cd21d8ec21a427724d1de5322ae9529456b8850c$bf local: 3154e7fc94010cb528f5f404ea80ee3a691376aa5899c8424534bcd0409d55e1)                             
##############################                                                                          
                                                                                                        
WARN [12-07|11:27:12.974] Synchronisation failed, dropping peer    peer=d64fd35320668d6d err="retrieved hash chain is invalid"                                                                                  
        ERROR[12-07|11:27:38.222] No proxy peers, cannot send Istanbul Validator Enodes Share message   
INFO [12-07|11:27:38.509] Ethereum handshake HASH                  id=d64fd35320668d6d conn=staticdial $ash=81cb03…f694af genesis="&{header:0xc0002f6240 uncles:[] transactions:[] randomness:0xc0000caa40 hash${v:[129 203 3 167 148 119 119 33 80 58 143 108 73 166 12 124 127 227 49 187 107 73 128 28 4 165 36 20 1$6 246 148 175]} size:{v:<nil>} td:<nil> ReceivedAt:0001-01-01 00:00:00 +0000 UTC ReceivedFrom:<nil>}"
ERROR[12-07|11:27:43.046]     
########## BAD BLOCK #########                      
Chain config: {ChainID: 12219 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 B$zantium: 0 Constantinople: 0  ConstantinopleFix: 0 Engine: istanbul}                                    
                                                                                                        
Number: 59040                                                                                           
Hash: 0x9482f7b73e6289490c8c834121829230f9e58162ea65bcc901e696f3d93b46cb                                
         0: cumulative: 0 gas: 0 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x0$00000000000000000000000000000000000000000000000000000000000000 logs: [0xc00177e0b0 0xc00177e160 0xc0017$e210 0xc00177e2c0 0xc00177e370 0xc00177e420 0xc00177e4d0 0xc00177e580 0xc00177e630 0xc00177e6e0 0xc0017$e790 0xc00177e840 0xc00177e8f0 0xc00177e9a0 0xc00177ea50 0xc00177eb00 0xc00177ebb0 0xc00177ec60 0xc0017$ed10 0xc00177edc0 0xc00177ee70 0xc00177ef20 0xc00177efd0 0xc0354da210 0xc0354da2c0 0xc0354da370 0xc0354$a420 0xc0354da4d0 0xc0354da580 0xc0354da630 0xc0354da6e0 0xc0354da790 0xc0354da840 0xc0354da8f0 0xc0354$a9a0 0xc0354daa50 0xc0354dab00 0xc0354dabb0 0xc0354dac60 0xc0354dad10 0xc0354dadc0 0xc0354dae70 0xc0354$af20 0xc0354dafd0 0xc0354db080 0xc0354db130 0xc0354db1e0 0xc0354db290 0xc0354db340 0xc0354db3f0 0xc0354$b4a0 0xc0354db550 0xc0354db600 0xc0354db6b0 0xc0354db760 0xc0354db810 0xc0354db8c0 0xc0354db970 0xc0354$ba20 0xc0354dbad0 0xc0354dbb80 0xc0354dbc30 0xc0354dbce0 0xc0354dbd90 0xc0354dbe40 0xc0354dbef0 0xc035d$1600 0xc035d516b0 0xc035d51760 0xc035d51810 0xc035d518c0 0xc035d51970 0xc035d51a20 0xc035d51ad0 0xc035d$1b80 0xc035d51c30 0xc035d51ce0 0xc035d51d90 0xc035d51e40 0xc035d51ef0 0xc02f5594a0 0xc02f559550 0xc02f5$9600 0xc02f5596b0 0xc02f559760 0xc02f559810 0xc02f5598c0 0xc02f559970 0xc02f559a20 0xc02f559ad0 0xc02f5$9b80 0xc02f559c30 0xc02f559ce0 0xc02f559d90 0xc02f559e40 0xc02f559ef0 0xc00a7fa8f0 0xc00a7fa9a0 0xc00a7$aa50 0xc00a7fab00 0xc00a7fabb0 0xc00a7fac60 0xc00a7fad10 0xc00a7fadc0 0xc00a7fae70 0xc00a7faf20 0xc00a7$afd0 0xc00a7fb080 0xc00a7fbd90 0xc00a7fbe40 0xc00a7fbef0 0xc00a60c000 0xc00a60c0b0 0xc00a60c160 0xc00a6$c210 0xc00a60c2c0 0xc00a60c370 0xc00a60c420 0xc00a60c4d0 0xc00a60c580 0xc00a60c630 0xc00a60c6e0 0xc00a6$c790 0xc00a60c840 0xc00a60c8f0 0xc00a60c9a0 0xc00a60ca50 0xc00a60cb00 0xc00a60cbb0 0xc00a60cc60 0xc00a6$cd10 0xc00a60cdc0 0xc00a60ce70 0xc00a60cf20 0xc00a60cfd0 0xc00a60d080 0xc00a60d130 0xc00a60d1e0 0xc00a6$d290 0xc00a60d340 0xc00a60d3f0 0xc00a60d4a0 0xc00a60d550 0xc00a60d600 0xc00a60d6b0 0xc00a60d760 0xc00a6$d810 0xc00a60d8c0 0xc00a60d970 0xc00a60da20 0xc00a60dad0 0xc00a60db80 0xc00a60dc30 0xc00a60dce0 0xc00a6$dd90 0xc00a60de40 0xc00a60def0 0xc00209a000 0xc00209a0b0 0xc00209a160 0xc00209a210 0xc00209a2c0 0xc0020$a370 0xc00209a420 0xc00209a4d0 0xc00209a580 0xc00209a630 0xc00209a6e0 0xc00209a790 0xc00209a840 0xc0020$a8f0 0xc00209a9a0 0xc00209aa50 0xc00209ab00 0xc00209abb0 0xc00209ac60 0xc00209ad10 0xc00209adc0 0xc0020$ae70 0xc00209af20 0xc00209afd0 0xc00209b080 0xc00209b130 0xc00209b1e0 0xc00209b290 0xc00209b340 0xc0020$b3f0 0xc00209b4a0 0xc00209b550 0xc00209b600 0xc00209b6b0 0xc00209b760 0xc00209b810 0xc00209b8c0 0xc0020$b970 0xc00209ba20] bloom: 00e000c6280aa0002080400904a008040d1100409403000140d0380080c040030880020048681$a204800c4002026784001111a00901c09c00c02020241014010880808800a048d0004280180320014009c02840000188e001040$00202c02204a00004a220411012954c90004000e0d08004000000390404818a85141000000894000080240c8020824000280200$84006000020006116014004800c0524000128412800088048007001c2280c0100810004042840042000800a1202088088c26420$1a050014052d1a9010180260230022200221081024410100c400902880c8500d00410030002800134211090080522140040880a$2200994802120c8840 state:                                                                               
                                                                                                        
```

Also note the proxy is reporting:
```
WARN [12-07|11:30:46.803] Failed to find the account               account=0x2c70c5F84525f31D043a42145f1945456D331C96 account url=                                                                              
```

**Comment by daithi-coombes** [comment]
I'm also seeing this in the logs, don't know is it related but prob because of above error?
```
Invalid round change certificate with preprepare. address=0x2c70c5F84525f31D043a42145f1945456D331C96 func=handlePreprepare  tag=handleMsg from=0xc5E3dB3218DD643DB1baFD3931D8CeD9723Ed
fb7 cur_seq=59040 cur_round=0 state="Waiting for new round" address=0x2c70c5F84525f31D043a42145f1945456D331C96 err="message in ROUND CHANGE certificate for wrong view"                                         INFO [12-07|11:36:10.836] Check round change message failed        address=0x2c70c5F84525f31D043a42145f1
945456D331C96 state="Waiting for new round" from=0x90a1Cb9CD4098B922e7a8EFCbfc56c9a793A74D7 cur_round=0 cur_seq=59040 func=handleRoundChange tag=handleMsg err="future message"                                 ERROR[12-07|11:36:12.371] Failed to decode message from payload    address=0x2c70c5F84525f31D043a42145f1
945456D331C96 func=handleMsg         cur_seq=59040 cur_round=0 state="Waiting for new round" address=0x2
c70c5F84525f31D043a42145f1945456D331C96 err="unauthorized address"
```

after about 15mins the following crash happens:
```
ERROR[12-07|11:51:14.375] Failed to decode message from payload    address=0x2c70c5F84525f31D043a42145f1
945456D331C96 func=handleMsg         cur_seq=59040 cur_round=0 state="Waiting for new round" address=0x2
c70c5F84525f31D043a42145f1945456D331C96 err="unauthorized address"                                      ERROR[12-07|11:51:14.433] Failed to decode message from payload    address=0x2c70c5F84525f31D043a42145f1
945456D331C96 func=handleMsg         cur_seq=59040 cur_round=0 state="Waiting for new round" address=0x2
c70c5F84525f31D043a42145f1945456D331C96 err="unauthorized address"                                      paic: node 157d2f5f7b9345ae3fbae75dc8b1ae89bf8dcd7c47bb0f306c1596865758c4da: unexpected EOF             
                                                                                                        goroutine 10142 [running]:                                                                              
github.com/ethereum/go-ethereum/trie.mustDecodeNode(0xc02c894180, 0x20, 0x20, 0x2099638, 0x0, 0x0, 0x0, 0x0, 0x0)                                                                                               
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/node.go:123 +0x1e3       github.com/ethereum/go-ethereum/trie.(*Database).node(0xc0003d72c0, 0xae45937b5f2f7d15, 0x89aeb1c85de7ba
3f, 0x300fbb477ccd8dbf, 0xdac458578696156c, 0x0, 0xc03559d778, 0xc03559d9a8)                                    /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/database.go:388 +0x1c5   
github.com/ethereum/go-ethereum/trie.(*Trie).resolveHash(0xc0071367d0, 0xc004021320, 0x20, 0x20, 0xc008a1dea0, 0x3, 0x41, 0x0, 0x0, 0xc03559d858, ...)                                                          
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:434 +0x140       github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0071367d0, 0x14e4e40, 0xc00716a5e0, 0xc008a1dea0,
 0x41, 0x41, 0x3, 0xc03559da48, 0x9951c7, 0xc02d59e000, ...)                                                    /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:167 +0xf8        
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0071367d0, 0x14e3000, 0xc018870c80, 0xc008a1dea0,
 0x41, 0x41, 0x2, 0x228, 0xc03559db70, 0xc03559dbe8, ...)                                                       /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:159 +0x6e8       
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0071367d0, 0x14e3000, 0xc001c02b40, 0xc008a1dea0,
 0x41, 0x41, 0x1, 0xf4ce279b09c5e303, 0x394923884726a281, 0xc03559dd08, ...)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:159 +0x6e8
github.com/ethereum/go-ethereum/trie.(*Trie).tryGet(0xc0071367d0, 0x14e3000, 0xc0045e5b80, 0xc008a1dea0,
 0x41, 0x41, 0x0, 0x20, 0xc0071367f0, 0x20, ...)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:159 +0x6e8
github.com/ethereum/go-ethereum/trie.(*Trie).TryGet(0xc0071367d0, 0xc0071367f0, 0x20, 0x20, 0xc0071367f0
, 0x20, 0x20, 0x102fdd0, 0xc0084c4a40)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/trie.go:133 +0x7b
github.com/ethereum/go-ethereum/trie.(*SecureTrie).TryGet(0xc0071367d0, 0xc02c894140, 0x20, 0x20, 0xc007
1367d0, 0x46b3b6, 0xc03559e04c, 0xc0068f1bf0, 0xad8244dfc1983601)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/trie/secure_trie.go:80 +0x7b
github.com/ethereum/go-ethereum/core/state.(*stateObject).GetCommittedState(0xc0355a7340, 0x14e9100, 0xc
000420d20, 0x26b392c7e54bc15e, 0x7adad4e6ad5ec16d, 0xb18c2e8e58fc2e0c, 0xd2e77362dce799c, 0x0, 0x0, 0x0,
 ...)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state/state_object.go:181

...

github.com/ethereum/go-ethereum/consensus/istanbul/backend.(*Backend).Finalize(0xc000108240, 0x14e8f80, 
0xc00025a000, 0xc003b47440, 0xc034ca3520, 0x2099638, 0x0, 0x0, 0x2099638, 0x0, ...)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/istanbul/backend/eng
ine.go:495 +0x39b
github.com/ethereum/go-ethereum/core.(*StateProcessor).Process(0xc0002a98a0, 0xc006a57a70, 0xc034ca3520,
 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/state_processor.go:88 +0x
7b1
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc00025a000, 0xc00792e9b0, 0x2, 0x2, 0xc
b463bd9f396e601, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:1325 +0xae3
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc00025a000, 0xc00792e9b0, 0x2, 0x2, 0x2
099638, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:1213 +0xb89
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc018de8000, 0xc00792e9
a0, 0x2, 0x2, 0x2, 0xc0002beba0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1
618 +0x417
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc018de8000, 0x1148
c80, 0xc0047d3798)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1
592 +0x79
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent-fm(0xc000000008, 0x1
306830)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:5
07 +0x2a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc018de8000, 0xc005185f80,
 0xc00792e940)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:5
19 +0x59
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:5
19 +0xaf
```

**Comment by daithi-coombes** [comment]
Implementing a new validator node to replace that one. Blocks are mining and issue doesn't seem to be recreated. Most likely the bad block happened during last nights upgrade, ie i've a corrupted chain.

**Comment by daithi-coombes** [comment]
Confirmed. Solution was to clear chain data and start again. Closing.
