### ISSUE TITLE
Crash when sending enode share message to proxy

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-blockchain#713]
### Expected Behavior

No crash
### Current Behavior

```
DEBUG[12-07|20:11:53.390] Removing p2p peer                        id=b89b31a4dcad6ea4 conn=staticdial duration=13m48.462s peers=0 req=false err="write tcp 172.17.0.2:48158->34.65.75.14:30503: write: broken pipe"
DEBUG[12-07|20:10:54.902] Sending Istanbul Validator Enodes Share payload to proxy peer 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb8b4db]

goroutine 1132 [running]:
github.com/ethereum/go-ethereum/consensus/istanbul/backend.(*Backend).sendValEnodesShareMsg(0xc0000ee000, 0x2, 0x2)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/istanbul/backend/val_enodes_share.go:167 +0x57b
created by github.com/ethereum/go-ethereum/consensus/istanbul/backend.(*Backend).sendValEnodesShareMsgs
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/istanbul/backend/val_enodes_share.go:94 +0x178
```

**Comment by asaj** [comment]
Logs from the proxy at the same (ish) times:
```
WARN [12-07|20:11:22.198] Stats login failed                       err="unknown account"
INFO [12-07|20:11:23.738] Imported new chain segment               blocks=1   txs=0    mgas=0.000   elapsed=30.438ms  mgasps=0.000  number=64024 hash=fe1b9d…c634ed cache=0.00B
INFO [12-07|20:11:28.731] Imported new chain segment               blocks=1   txs=0    mgas=0.000   elapsed=31.610ms  mgasps=0.000  number=64025 hash=f56cc8…aded6e cache=0.00B
WARN [12-07|20:11:33.041] Failed to find the account               account=0x6729622cB0535f168e744c4ecBc380fb230cB9b2 account url=
WARN [12-07|20:11:33.042] Stats login failed                       err="unknown account"
INFO [12-07|20:11:33.840] Imported new chain segment               blocks=1   txs=0    mgas=0.000   elapsed=30.361ms  mgasps=0.000  number=64026 hash=bc926e…ba11d1 cache=0.00B
INFO [12-07|20:11:37.929] Imported new chain segment               blocks=1   txs=0    mgas=0.000   elapsed=31.082ms  mgasps=0.000  number=64027 hash=df0006…637910 cache=0.00B
WARN [12-07|20:11:43.650] Failed to find the account               account=0x6729622cB0535f168e744c4ecBc380fb230cB9b2 account url=
WARN [12-07|20:11:43.650] Stats login failed                       err="unknown account"
WARN [12-07|20:11:54.259] Failed to find the account               account=0x6729622cB0535f168e744c4ecBc380fb230cB9b2 account url=
WARN [12-07|20:11:54.259] Stats login failed                       err="unknown account"
INFO [12-07|20:11:58.779] Ethereum handshake HASH                  id=f49da4b98ba9ea1d conn=inbound    hash=81cb03…f694af genesis="&{header:0xc0000f0fc0 uncles:[] transactions:[] randomness:0xc0000d0500 hash:{v:[129 203 3 167 148 119 119 33 80 58 143 108 73 166 12 124 127 227 49 187 107 73 128 28 4 165 36 20 146 246 148 175]} size:{v:<nil>} td:<nil> ReceivedAt:0001-01-01 00:00:00 +0000 UTC ReceivedFrom:<nil>}"
WARN [12-07|20:12:05.026] Stats login failed                       err="json: cannot unmarshal string into Go value of type map[string][]string"
```

**Comment by diminator** [comment]
What's the process for triggering this error?

**Comment by diminator** [comment]
`err="unknown account"` seems to point at no etherbase for the proxy

**Comment by diminator** [comment]
I think we can fix tah

**Comment by nategraf** [comment]
@kevjue do you think this issue might still exist, or is it obsolete with all the new changes?
