### ISSUE TITLE
panic: leveldb: internal key "", len=0: invalid length

### ISSUE THREAD

**Issue by daithi-coombes** [celo-org/celo-blockchain#720]
### Expected Behavior
Sync and validate

### Current Behavior
When starting a validator from scratch it tries sync and then throws `golang panic`. The restart after this always produces a bad block, meaning the chain datadir has to then be deleted again. But the `panic` will be thrown again, then restart into bad block, and back.

```
ERROR[12-08|14:31:46.137] Failed to decode message from payload    address=0x2c70c5F84525f31D043a42145f1
945456D331C96 func=handleMsg         cur_seq=9662 cur_round=0 state="Waiting for new round" address=0x2$
70c5F84525f31D043a42145f1945456D331C96 err="unauthorized address"
panic: leveldb: internal key "", len=0: invalid length

goroutine 454 [running]:
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.internalKey.assert(0xc034da1$
b1, 0x0, 0x6377a)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/gole$
eldb/leveldb/key.go:111 +0x15c
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.internalKey.ukey(0xc034da13b$
, 0x0, 0x6377a, 0x63856, 0xc0097bbc50, 0x20)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/gole$
eldb/leveldb/key.go:116 +0x3f
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb.(*iComparer).Compare(0xc0002$
fdc0, 0xc034da13b1, 0x0, 0x6377a, 0xc0097bbc50, 0x28, 0x28, 0xffffffffffffffff)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/golev
eldb/leveldb/comparer.go:38 +0x4c
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table.(*block).seek.func1(0x8
568, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/syndtr/golev
eldb/leveldb/table/reader.go:71 +0x1c3
invalid spdelta sort.Search 0x549480 0x5494d2 0x10836d -1
sort.Search(0x0, 0x857200, 0x855e00)
        /usr/local/go/src/sort/search.go:66 +0x52
runtime: unexpected return pc for vendor/golang_org/x/net/idna.(*Profile).process called from 0xc0060931
d000
stack: frame={sp:0xc02ebd00f7, fp:0xc02ebd0207} stack=[0xc02ebc8000,0xc02ebd8000)
000000c02ebcfff7:  0000000000000000  0000000006377a00 
000000c02ebd0007:  0000000006385600  0000c0097bbc5000 
000000c02ebd0017:  0000000000002000  0000000000002800 
000000c02ebd0027:  ffffffffffffff00  00000001306820ff 
000000c02ebd0037:  0000c02ebd007800  0000000000000300 
000000c02ebd0047:  0000000006385600  0000c034da12d500 
000000c02ebd0057:  0000c02ebd00e000  000000006d8cc300 
000000c02ebd0067:  0000c0002cfdc000  0000c034da13b100 
000000c02ebd0077:  0000000000000000  0000000006377a00 
000000c02ebd0087:  0000c0097bbc5000  0000000000002800 
000000c02ebd0097:  0000000000002800  ffffffffffffff00 
000000c02ebd00a7:  12f3ae00000000ff  0000000000000000 
000000c02ebd00b7:  000000014e6b0000  0000000012f3af00 
000000c02ebd00c7:  0000c0002cfdc000  0000c01b1a7f8000 
000000c02ebd00d7:  0000c02ebd014000  0000c02ebd011800 
000000c02ebd00e7:  000000005494d200  0000000000856800 <vendor/golang_org/x/net/idna.(*Profile).process+1
344> 
000000c02ebd00f7: <0000000000000000  0000000000857200 <vendor/golang_org/x/net/idna.validateAndMap+368> 
000000c02ebd0107:  0000000000855e00 <vendor/golang_org/x/net/idna.ToASCII+0>  0000000000856800 <vendor/g
olang_org/x/net/idna.(*Profile).process+1344> 
000000c02ebd0117:  0000c02ebd018000  000000006ce45100 
000000c02ebd0127:  0000000000aa9800 <github.com/ethereum/go-ethereum/accounts/usbwallet.(*trezorDriver).
trezorSign+960>  0000c02ebd014000 
000000c02ebd0137:  0000c009b3e35000  000000006d8b0000 
000000c02ebd0147:  0000c01b1a7f8000  0000000000000000 
000000c02ebd0157:  000000014e6b0000  0000c0002cfdc000 
000000c02ebd0167:  0000c0097bbc5000  0000000000002800 
000000c02ebd0177:  0000000000002800  0000c02ebd01f000 
000000c02ebd0187:  000000006cecd100  0000c01b1a7f8000 
000000c02ebd0197:  000000014e6b0000  0000c0002cfdc000 
000000c02ebd01a7:  0000000000000000  0000000000aa9800 <github.com/ethereum/go-ethereum/accounts/usbwalle
t.(*trezorDriver).trezorSign+960> 
000000c02ebd01b7:  0000c0097bbc5000  0000000000002800
000000c02ebd01c7:  0000000000002800 0000000000000800
000000c02ebd01d7:  0000c01b1a688000  0000000000000000 
000000c02ebd01e7:  0000c02ebd020800  0000c02ebd02e000 
000000c02ebd01f7:  000000006d402500 !0000c0060931d000 
000000c02ebd0207: >0000c0097bbc5000  0000000000002800 
000000c02ebd0217:  0000000000002800  0000000000000000 
000000c02ebd0227:  0000000000000100  0000c0060931d000 
000000c02ebd0237:  0000c00003a00000  007f57673ad00000 
000000c02ebd0247:  0000000000000000  0000c00cacbec900 
000000c02ebd0257:  0000c02ebd02a000  000000004897e100 
000000c02ebd0267:  0000000130682000  0000c02ebd02b000 
000000c02ebd0277:  0000000046a20800  0000000000000800 
000000c02ebd0287:  0000000130682000  0000000000000100 
000000c02ebd0297:  0000c01b1a7f8000  0000c0060931d000 
000000c02ebd02a7:  000000006c9f2600  0000c0003f31c000 
000000c02ebd02b7:  0000c009b3e34800  0000c0003f318000 
000000c02ebd02c7:  0000c03a7ea14e00  0000000000000000 
000000c02ebd02d7:  0000000000000600  0000c02ebd036800 
000000c02ebd02e7:  000000006d4caa00  0000c019bd8c3000 
000000c02ebd02f7:  0000c0097bbc5000  0000000000002800 
vendor/golang_org/x/net/idna.(*Profile).process(0xc0097bbc5000, 0x2800, 0x2800, 0x0, 0x100, 0xc0060931d0
00, 0xc00003a00000, 0x7f57673ad00000)
        /usr/local/go/src/vendor/golang_org/x/net/idna/idna.go:301 +0x540
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:5
19 +0xaf
```

**Comment by daithi-coombes** [comment]
Seems blank key is being passed to level db here: https://github.com/syndtr/goleveldb/blob/master/leveldb/key.go#L111

also looking at the memdump it could be related to `trezor` implementation

**Comment by tkporter** [comment]
At the moment we don't support Trezor hardware wallets, which probably explains what's happening here. We have #190 and #225 to track this work
