### ISSUE TITLE
[loop] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by daithi-coombes** [celo-org/celo-blockchain#723]
### Expected Behavior

Node will sync without corrupting the chain

### Current Behavior

Whilst syncing there are golang `panic`'s causing the validating node to crash. Docker restarts this but eventually the crash will cause a `bad block` and force start syncing from beginning again.
(may be related #720 ?)

every 10 - 30 seconds:
```
DEBUG[12-08|17:24:32.700] Synchronisation terminated               elapsed=870.596676ms                 
panic: runtime error: invalid memory address or nil pointer dereference                                 [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xaf3dad]                                
                                                                                                        goroutine 847 [running]:                                                                                github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc000464000, 0xc02b4f52c0, 0x
c02b78d680, 0x0, 0x0, 0xc00023bc00)                                                                     
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:8
53 +0x15ad                                                                                              
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc000464000, 0xc02b4f52c0, 0x
aa11cb48d96349df, 0x62bfe809da30b74, 0x52d0d6058f27a9c9, 0xb3b281c84066f97b, 0xc001cd56e0, 0x0, 0x0)    
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:4
64 +0x37d                                                                                               
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc000464000, 0xc00065e750, 0x1
0, 0xaa11cb48d96349df, 0x62bfe809da30b74, 0x52d0d6058f27a9c9, 0xb3b281c84066f97b, 0xc001cd56e0, 0x0, 0x0
, ...)                                                                                                  
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:4
33 +0x362
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc000464000, 0xc00065e750, 0x1
0, 0xaa11cb48d96349df, 0x62bfe809da30b74, 0x52d0d6058f27a9c9, 0xb3b281c84066f97b, 0xc001cd56e0, 0x0, 0x2
, ...)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:3
51 +0x91
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0xc0000e7d10, 0xc0005f8480)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:200 +0x313
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:155 +0x1df
```

**Comment by daithi-coombes** [comment]
the container still restarted, then synced a bit. But now its permentaly stuck on crash at block `24845`

now every time it tries get these headers `fromnum=24845` I get:
```
DEBUG[12-08|17:58:33.516] Fetching batch of headers                id=d64fd35320668d6d conn=staticdial c
ount=1  fromnum=24844 skip=0  reverse=false                                                             
DEBUG[12-08|17:58:33.565] Fetching batch of headers                id=d64fd35320668d6d conn=staticdial c
ount=1  fromnum=24845 skip=0  reverse=false
DEBUG[12-08|17:58:33.613] Synchronisation terminated               elapsed=869.427036ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xaf3dad]

goroutine 793 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc0004be000, 0xc02be4d860, 0x
c00106ad80, 0x0, 0x0, 0xc0002e9180)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:8
53 +0x15ad
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc0004be000, 0xc02be4d860, 0x
5cae859aacb69705, 0x1a3ec2cbcd8d6532, 0xcdad27536734cda9, 0x8dac16fa05309208, 0xc001371760, 0x0, 0x0)
```

**Comment by daithi-coombes** [comment]
I haven't been able to re-create this error since. Close?

**Comment by timmoreton** [comment]
looks like @trottier saw the same : 
https://gist.github.com/trottier/24a3d238d06a075468030c7e970481f0

**Comment by tkporter** [comment]
@daithi-coombes Do you have any more logs on hand? What OS were you running this on?

I've found https://github.com/ethereum/go-ethereum/issues/18994 and https://github.com/ethereum/go-ethereum/issues/18388, which suggest that it could be related to using too many file descriptors.

What I'm most interested in is the log that's printed when you first start geth that includes: `Allocated cache and file handles`

**Comment by tkporter** [comment]
One simple solution is to just check if https://github.com/celo-org/celo-blockchain/blob/master/eth/downloader/downloader.go#L853 is nil before doing anything, but that shouldn't happen unless there's an issue elsewhere. Going to wait before making that change to see if I could get more info

**Comment by daithi-coombes** [comment]
@tkporter 
```
$ uname -a
Linux sgx0 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/*release*
...
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
...
```

the issue hasn't reapeared since, so not re-creatable unforunatley. Also validator currently running has replaced old container

**Comment by oneeman** [comment]
Closing this and #828 as stale.  There were 3 reports (two here and one in #828) were all reported around the end of 2019, beginning of 2020, and the problem hasn't reappeared since as far as we know.

As @tkporter pointed out above, there were issues on go-ethereum with the same crash, suggesting chain corruption and/or too many open files.  But the celo repo had already included the upstream fix for the issue that was causing it for go-ethereum (and which was only on MacOS), so it's unlikely to be exactly the same.  Still, since it hasn't happened in nearly a year it has likely been fixed already, and at any rate we can't identify the cause without someone being able to reproduce the cause.
