### ISSUE TITLE
Stuck syncing block 29554 - golang panic - boot loop

### ISSUE THREAD

**Issue by daithi-coombes** [celo-org/celo-blockchain#739]
### Expected Behavior
Will sync past block 29554

### Current Behavior
Validator is crashing and restarting every min with the following errors

On boot its rewinds to block `29553`
```
INFO [12-10|13:28:02.161] Initialising Ethereum protocol           versions=[64] network=12219          
WARN [12-10|13:28:02.163] Head state missing, repairing chain      number=29554 hash=8cc457…02fb72      
INFO [12-10|13:28:02.164] Rewound blockchain to past state         number=29553 hash=fdbeab…735adf   
INFO [12-10|13:28:02.164] Loaded most recent local header          number=29554 hash=8cc457…02fb72 td=29
555 age=5d14h10m                                                                                        
INFO [12-10|13:28:02.164] Loaded most recent local full block      number=29553 hash=fdbeab…735adf td=29
554 age=5d14h10m                                                                                        
INFO [12-10|13:28:02.165] Loaded most recent local fast block      number=29554 hash=8cc457…02fb72 td=29
555 age=5d14h10m
```

Then on block `29554` the following `warnings`
```
INFO [12-10|13:28:12.210] Block synchronisation started 
INFO [12-10|13:28:12.211] Mining aborted due to sync  
WARN [12-10|13:28:12.211] Synchronisation failed, retrying         err="block download canceled (request
ed)"
INFO [12-10|13:28:12.219] Commit new mining work                   number=29554 sealhash=bf2233…e67ef4 u
ncles=0 txs=0 gas=0 fees=0 elapsed=3.642ms
WARN [12-10|13:28:12.219] Block sealing failed                     err=unauthorized
```

Then a golang `panic`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0xaf3dad]

goroutine 184 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc0000e6380, 0xc0015d5590, 0x
c000b74fc0, 0x0, 0x0, 0xc000080700)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:8
53 +0x15ad
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc0000e6380, 0xc0015d5590, 0x
ac79d96ec0a5fd1, 0xf30e100e6b19dbcb, 0xbdc14e4d7e55ce24, 0x9825432b929c9b9, 0xc0015ed820, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:4
64 +0x37d
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc0000e6380, 0xc0014ead80, 0x1
0, 0xac79d96ec0a5fd1, 0xf30e100e6b19dbcb, 0xbdc14e4d7e55ce24, 0x9825432b929c9b9, 0xc0015ed820, 0x0, 0x0,
 ...)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:4
33 +0x362
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc0000e6380, 0xc0014ead80, 0x1
0, 0xac79d96ec0a5fd1, 0xf30e100e6b19dbcb, 0xbdc14e4d7e55ce24, 0x9825432b929c9b9, 0xc0015ed820, 0x0, 0xc0
0034a7c8, ...)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:3
51 +0x91
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0xc0003225a0, 0xc00154de00)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:200 +0x313
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:155 +0x1df
```

container then restarts and back to rewinding to block `29553`.

**Comment by daithi-coombes** [comment]
clear chain data and resync has produced bad block at `31378`

```
Error: invalid merkle root (remote: 11139b70f7aa51e62f9cbdf6edfa9ae7c2f441fd349439fdc9a6876be915bfaa loc
al: dc847a762dc7abbd8ed427fb6a746282594154c6f3b84ba1d159f433aec914e6)
```

**Comment by nategraf** [comment]
@daithi-coombes have you seen this with any later builds / when you switched off of SGX?

**Comment by mcortesi** [comment]
Will close for now
