### ISSUE TITLE
Authorize Validator Signing Key Not Working

### ISSUE THREAD

**Issue by joesixpack** [celo-org/celo-blockchain#752]
$ celocli account:authorize --from $CELO_VALIDATOR_ADDRESS --role validator --signature 0x$CELO_VALIDATOR_SIGNER_SIGNATURE --signer 0x$CELO_VALIDATOR_SIGNER_ADDRESS
Error: Unable to parse signature
    at parseSignatureWithoutPrefix (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/@celo/utils/src/signatureUtils.ts:147:9)
    at Object.parseSignature (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/@celo/utils/src/signatureUtils.ts:129:10)
    at AccountsWrapper.parseSignatureOfAddress (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/@celo/contractkit/src/wrappers/Accounts.ts:298:12)
    at Authorize.<anonymous> (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/src/commands/account/authorize.ts:37:26)
    at Generator.next (<anonymous>)
    at fulfilled (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/lib/commands/account/authorize.js:4:58)

**Comment by joesixpack** [comment]
Found the problem.  It was truncated with the $ in nano (i.e. there was nothing to the right).
